build:
  environment:
    php:
      version: '7.2'
    node: 'v8.15.0'
    variables:
      APP_ENV: test
  dependencies:
    before:
      - make install
  project_setup:
    before:
      - mysql -e "CREATE DATABASE myblog;"
  tests:
    override:
      -
        command: make check
        coverage:
          file: ./docs/coverage/xml
          format: php-clover
filter:
  excluded_paths:
    - vendor/*
checks:
  php: true
coding_style:
  php:
    spaces:
      before_parentheses:
        function_declaration: false
        closure_definition: true
        function_call: false
        if: true
        for: true
        while: true
        switch: true
        catch: true
        array_initializer: false
