build:
  environment:
    php:
      version: '7.2'
    node: 'v8.15.0'
    variables:
      TEST: 1
  dependencies:
    before:
      - make install
  project_setup:
    before:
      - mysql -e "CREATE DATABASE myblog;"
  tests:
    override:
      -
        command: make check
        coverage:
          file: ./docs/coverage/xml
          format: php-clover
filter:
  excluded_paths:
    - vendor/*
