build:
  environment:
    php:
      version: '7.2'
    node: 'v8.15.0'
    variables:
      TEST: 1
  dependencies:
    before:
      - composer install
  project_setup:
    before:
      - mysql -e "CREATE DATABASE myblog;"
  tests:
    override:
      -
        command: ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php ./tests/ --coverage-clover ./docs/coverage/xml --whitelist ./src
        coverage:
          file: ./docs/coverage/xml
          format: php-clover
filter:
  excluded_paths:
    - vendor/*
