language: php
php:
  - '7.1'
  - '7.2'

env:
  - TEST=1

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE myblog;"

script:
  - make check
  - ./vendor/bin/codacycoverage clover ./docs/coverage/xml

