language: php
php:
  - '7.1'
  - '7.2'
script:
  - composer install
  - ./vendor/bin/phpstan analyse src tests --level 4
  - phpunit --bootstrap ./vendor/autoload.php ./tests/ --coverage-clover ./docs/coverage/xml --whitelist ./src
  - ./vendor/bin/codacycoverage clover ./docs/coverage/xml

